import './styles.css'
import { supabase, api, adminApi } from './api.js'

const root=document.querySelector('#app'), toasts=document.querySelector('#toast-root')
const s={data:null,tab:'games',mode:'login',game:null,timer:null}
const N=new Intl.NumberFormat('vi-VN'), f=n=>N.format(Number(n||0)), e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const wait=ms=>new Promise(r=>setTimeout(r,ms))
function toast(m,t=''){const x=document.createElement('div');x.className=`toast ${t}`;x.textContent=m;toasts.append(x);setTimeout(()=>x.classList.add('show'),10);setTimeout(()=>x.remove(),3200)}
function err(m=''){return ({'Invalid login credentials':'Email hoặc mật khẩu không đúng.','Email not confirmed':'Hãy xác nhận email trước khi đăng nhập.','TOO_FAST':'Phiên chơi quá nhanh nên không được cộng coin.','IMPOSSIBLE_SCORE':'Điểm vượt ngưỡng hợp lý nên bị từ chối.','SESSION_EXPIRED':'Phiên chơi đã hết hạn.','SESSION_ALREADY_FINISHED':'Phiên này đã được xử lý.','BELOW_MIN_WITHDRAWAL':'Chưa đạt mức rút tối thiểu.','INSUFFICIENT_BALANCE':'Số dư coin không đủ.','TOO_MANY_SESSIONS':'Bạn mở quá nhiều phiên game.'})[m]||m}
async function load(a='bootstrap',draw=true){s.data=await api(a);if(draw)render();return s.data}

function auth(){const login=s.mode==='login';root.innerHTML=`<main class="auth"><section class="brand"><div class="coin">G</div><div><h1>Gamezcoin</h1><p>Chơi Game & Kiếm Thưởng</p></div></section><section class="card authbox"><div class="switch"><button data-mode="login" class="${login?'on':''}">Đăng nhập</button><button data-mode="signup" class="${!login?'on':''}">Đăng ký</button></div><form id="authf">${login?'':'<label>Tên hiển thị<input name="name" minlength="2" maxlength="40" required></label>'}<label>Email<input name="email" type="email" required></label><label>Mật khẩu<input name="pass" type="password" minlength="6" required></label>${login?'':'<label>Mã giới thiệu (không bắt buộc)<input name="ref" maxlength="16"></label>'}<button class="primary" type="submit">${login?'Đăng nhập':'Tạo tài khoản'}</button></form><button id="google" class="google">Đăng nhập bằng Google</button><small>Tài khoản và coin được lưu trên server, dùng chung giữa nhiều thiết bị.</small></section></main>`
root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{s.mode=b.dataset.mode;auth()})
root.querySelector('#authf').onsubmit=async ev=>{ev.preventDefault();const d=new FormData(ev.currentTarget),email=String(d.get('email')).trim(),password=String(d.get('pass'));try{if(login){const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}else{const{data,error}=await supabase.auth.signUp({email,password,options:{data:{display_name:String(d.get('name')).trim(),referral_code:String(d.get('ref')||'').trim().toUpperCase()||null}}});if(error)throw error;if(!data.session){toast('Đã đăng ký. Hãy xác nhận email rồi đăng nhập.','ok');s.mode='login';auth()}}}catch(x){toast(err(x.message),'bad')}}
root.querySelector('#google').onclick=async()=>{const{error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}});if(error)toast(err(error.message),'bad')}
}

const nav=(id,ic,tx)=>`<button data-tab="${id}" class="${s.tab===id?'on':''}"><b>${ic}</b><small>${tx}</small></button>`
function render(){if(!s.data)return auth();const d=s.data;root.innerHTML=`<div class="shell"><header><div><small>GAMEZCOIN</small><strong>${e(d.profile?.display_name||'Người chơi')}</strong></div><button data-tab="wallet" class="balance"><span>G</span>${f(d.wallet?.balance)} coin</button></header><main id="view"></main><nav>${nav('games','🎮','Game')}${nav('checkin','📅','Điểm danh')}${nav('wallet','🪙','Ví')}${nav('ref','👥','Giới thiệu')}${nav('account','👤','Tài khoản')}</nav></div>`;root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{s.tab=b.dataset.tab;render()});({games,checkin,wallet,ref:referral,account})[s.tab]()}

function games(){const v=root.querySelector('#view'),gs=s.data.games||[];v.innerHTML=`<section class="hero"><div><i>KHÔNG GIỚI HẠN COIN/NGÀY</i><h2>Chơi càng tốt, nhận càng nhiều</h2><p>Server xác minh phiên chơi trước khi cộng coin.</p></div><div class="coin big">G</div></section><h3>Mini game</h3><div class="games">${gs.map((g,i)=>`<article class="card game"><div class="gi">${['⚡','🎯','🧠'][i%3]}</div><div><strong>${e(g.name)}</strong><small>${e(g.description)}</small><em>+${f(g.coin_per_point)} coin / điểm</em></div><button data-play="${e(g.id)}">Chơi</button></article>`).join('')}</div>`;v.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>start(b.dataset.play))}
function modal(html){let m=document.querySelector('#gm');if(!m){m=document.createElement('div');m.id='gm';m.className='modal';document.body.append(m)}m.innerHTML=`<section class="stage">${html}</section>`}
function close(){clearInterval(s.timer);clearTimeout(s.timer);document.querySelector('#gm')?.remove();s.game=null}
async function start(id){try{modal('<div class="loader"></div><p>Đang tạo phiên chơi...</p>');const r=await api('start_game',{game_id:id});s.game={...r,local:Date.now()};if(id==='tap-rush')tap();else if(id==='target-hunt')target();else memory()}catch(x){close();toast(err(x.message),'bad')}}
async function finish(score){const g=s.game;if(!g)return;modal(`<div class="loader"></div><p>Server đang xác minh ${f(score)} điểm...</p>`);try{const w=Math.max(0,Number(g.game.min_duration_ms||0)+300-(Date.now()-g.local));if(w)await wait(w);const r=await api('finish_game',{session_id:g.session.id,score}),c=Number(r.result?.game_coin||0),b=Number(r.result?.referral_invitee_coin||0);modal(`<div class="trophy">🏆</div><h2>Hoàn thành</h2><strong class="earned">+${f(c)} coin</strong>${b?`<p>Thưởng giới thiệu +${f(b)} coin</p>`:''}<button id="done" class="primary">Nhận thưởng</button>`);document.querySelector('#done').onclick=async()=>{close();await load()}}catch(x){modal(`<h2>Không được cộng coin</h2><p>${e(err(x.message))}</p><button id="done" class="secondary">Đóng</button>`);document.querySelector('#done').onclick=close}}
function tap(){let sc=0,t=10;modal(`<div class="gamehead"><b>Tap Rush</b><b id="time">10s</b></div><strong id="score" class="score">0</strong><button id="tap" class="tap">CHẠM!</button>`);const b=document.querySelector('#tap');b.onpointerdown=ev=>{ev.preventDefault();sc++;document.querySelector('#score').textContent=sc};s.timer=setInterval(()=>{t--;document.querySelector('#time').textContent=t+'s';if(t<=0){clearInterval(s.timer);b.disabled=true;finish(sc)}},1000)}
function target(){let sc=0,t=15;modal(`<div class="gamehead"><b>Target Hunt</b><b id="time">15s</b></div><div id="area" class="area"><button id="target" class="target">+1</button></div><p>Điểm: <b id="score">0</b></p>`);const a=document.querySelector('#area'),b=document.querySelector('#target'),move=()=>b.style.transform=`translate(${Math.random()*Math.max(1,a.clientWidth-64)}px,${Math.random()*Math.max(1,a.clientHeight-64)}px)`;move();b.onpointerdown=ev=>{ev.preventDefault();sc++;document.querySelector('#score').textContent=sc;move()};s.timer=setInterval(()=>{t--;document.querySelector('#time').textContent=t+'s';if(t<=0){clearInterval(s.timer);b.disabled=true;finish(sc)}},1000)}
function memory(){let round=1,score=0;const go=()=>{const len=round+2,seq=Array.from({length:len},()=>Math.floor(Math.random()*10)).join('');modal(`<div class="gamehead"><b>Chuỗi Trí Nhớ</b><b>${round}/5</b></div><div id="seq" class="seq">${seq}</div><div id="mi" class="hide"><input id="ans" inputmode="numeric" maxlength="${len}" placeholder="Nhập chuỗi"><button id="check" class="primary">Kiểm tra</button></div><p>Điểm: ${score}</p>`);setTimeout(()=>{if(!document.querySelector('#seq'))return;document.querySelector('#seq').textContent='••••••••';document.querySelector('#mi').classList.remove('hide');document.querySelector('#check').onclick=()=>{if(document.querySelector('#ans').value.trim()===seq){score+=len;if(round++>=5)finish(score);else go()}else finish(score)}},1800+round*250)};go()}

function checkin(){const v=root.querySelector('#view'),r=Number(s.data.settings?.daily_checkin_coin||100);v.innerHTML=`<section class="card center"><div class="emoji">📅</div><h2>+${f(r)} coin</h2><p>Mỗi ngày nhận một lần. Coin chơi game vẫn không giới hạn theo ngày.</p><button id="claim" class="primary">Điểm danh ngay</button></section>`;v.querySelector('#claim').onclick=async()=>{try{const x=await api('checkin');toast(x.result.claimed?`+${f(x.result.reward_coin)} coin`:'Hôm nay bạn đã điểm danh.','ok');await load('dashboard')}catch(x){toast(err(x.message),'bad')}}}
const st=x=>({pending:'Đang chờ',paid:'Đã thanh toán',rejected:'Từ chối'})[x]||x
async function wallet(){const v=root.querySelector('#view');v.innerHTML='<div class="loader"></div>';try{await load('dashboard',false)}catch(x){toast(err(x.message),'bad')}const d=s.data,w=d.wallet||{},min=Number(d.settings?.min_withdrawal_coin||20000);v.innerHTML=`<section class="wallet"><small>SỐ DƯ</small><h1>${f(w.balance)} <span>coin</span></h1><p>Đã kiếm ${f(w.lifetime_earned)} · Đã rút ${f(w.lifetime_withdrawn)}</p></section><section class="card"><h3>Rút tiền</h3><form id="wd"><label>Số coin<input name="amount" type="number" min="${min}" required placeholder="Tối thiểu ${min}"></label><label>Phương thức<select name="method"><option value="momo">MoMo</option><option value="bank">Ngân hàng</option></select></label><label>Chủ tài khoản<input name="name" required></label><label>SĐT / số tài khoản<input name="number" required></label><label>Tên ngân hàng<input name="bank"></label><button class="primary">Gửi yêu cầu rút</button></form><small>Nếu admin từ chối, coin được hoàn tự động.</small></section><section class="card"><h3>Lịch sử rút</h3>${(d.withdrawals||[]).map(x=>`<div class="row"><span>${f(x.coin_amount)} coin<small>${new Date(x.created_at).toLocaleString('vi-VN')}</small></span><b class="${x.status}">${st(x.status)}</b></div>`).join('')||'<p>Chưa có yêu cầu.</p>'}</section><section class="card"><h3>Biến động coin</h3>${(d.ledger||[]).map(x=>`<div class="row"><span>${e(x.description)}<small>${new Date(x.created_at).toLocaleString('vi-VN')}</small></span><b class="${Number(x.amount)>0?'plus':'minus'}">${Number(x.amount)>0?'+':''}${f(x.amount)}</b></div>`).join('')||'<p>Chưa có giao dịch.</p>'}</section>`;v.querySelector('#wd').onsubmit=async ev=>{ev.preventDefault();const d=new FormData(ev.currentTarget);try{await api('withdraw',{coin_amount:Number(d.get('amount')),method:d.get('method'),account_name:d.get('name'),account_number:d.get('number'),bank_name:d.get('bank')});toast('Đã gửi yêu cầu rút.','ok');await load('dashboard')}catch(x){toast(err(x.message),'bad')}}}
function referral(){const d=s.data,v=root.querySelector('#view'),code=d.profile?.referral_code||'';v.innerHTML=`<section class="card center"><div class="emoji">👥</div><p>Mã giới thiệu của bạn</p><div class="refcode">${e(code)}</div><button id="copy" class="primary">Sao chép mã</button></section><section class="card"><div class="row"><span>Bạn nhận</span><b class="plus">+${f(d.settings?.referral_inviter_coin)} coin</b></div><div class="row"><span>Người được mời nhận</span><b class="plus">+${f(d.settings?.referral_invitee_coin)} coin</b></div><small>Thưởng sau phiên game hợp lệ đầu tiên của tài khoản được mời.</small></section>`;v.querySelector('#copy').onclick=async()=>{await navigator.clipboard?.writeText(code);toast('Đã sao chép.','ok')}}
function account(){const d=s.data,v=root.querySelector('#view');v.innerHTML=`<section class="card center"><div class="avatar">${e((d.profile?.display_name||'G')[0])}</div><h2>${e(d.profile?.display_name)}</h2><p>${e(d.user?.email)}</p>${d.is_admin?'<b class="adminbadge">ADMIN</b>':''}</section><section class="card"><form id="pf"><label>Tên hiển thị<input name="name" value="${e(d.profile?.display_name)}" minlength="2" maxlength="40" required></label><button class="secondary">Lưu tên</button></form></section>${d.is_admin?'<button id="admin" class="adminbtn">🛡️ Trang quản trị</button>':''}<button id="logout" class="danger">Đăng xuất</button>`;v.querySelector('#pf').onsubmit=async ev=>{ev.preventDefault();try{await api('update_profile',{display_name:new FormData(ev.currentTarget).get('name')});await load();toast('Đã lưu.','ok')}catch(x){toast(err(x.message),'bad')}};v.querySelector('#logout').onclick=()=>supabase.auth.signOut();v.querySelector('#admin')?.addEventListener('click',admin)}

async function admin(){const v=root.querySelector('#view');v.innerHTML='<div class="loader"></div>';try{const[o,u,w]=await Promise.all([adminApi('overview'),adminApi('users',{per_page:100}),adminApi('withdrawals',{status:'all'})]);v.innerHTML=`<button id="back" class="secondary">← Quay lại</button><h2>Quản trị Gamezcoin</h2><div class="stats"><div>Người dùng<b>${f(o.users)}</b></div><div>Coin lưu hành<b>${f(o.circulating_coin)}</b></div><div>Chờ rút<b>${f(o.pending_withdrawals)}</b></div><div>Coin chờ rút<b>${f(o.pending_coin)}</b></div></div><section class="card"><h3>Yêu cầu rút</h3>${w.withdrawals.map(x=>`<article class="adminrow"><div><b>${e(x.profile?.display_name||x.user_id)}</b><small>${e(x.method.toUpperCase())} · ${e(x.account_name)} · ${e(x.account_number)} ${e(x.bank_name||'')}</small></div><strong>${f(x.coin_amount)} coin</strong>${x.status==='pending'?`<div><button data-ap="${x.id}">Đã thanh toán</button><button data-rj="${x.id}">Từ chối</button></div>`:`<i>${st(x.status)}</i>`}</article>`).join('')||'<p>Chưa có.</p>'}</section><section class="card"><h3>Người dùng</h3>${u.users.map(x=>`<div class="row"><span>${e(x.profile?.display_name||'Người chơi')}<small>${e(x.email||'')}</small></span><span><b>${f(x.wallet?.balance)} coin</b> <button data-adj="${x.id}">±</button></span></div>`).join('')}</section>`;v.querySelector('#back').onclick=()=>{s.tab='account';render()};v.querySelectorAll('[data-ap]').forEach(b=>b.onclick=()=>processWd(b.dataset.ap,'approve'));v.querySelectorAll('[data-rj]').forEach(b=>b.onclick=()=>processWd(b.dataset.rj,'reject'));v.querySelectorAll('[data-adj]').forEach(b=>b.onclick=()=>adjust(b.dataset.adj))}catch(x){v.innerHTML=`<p>${e(err(x.message))}</p>`}}
async function processWd(id,decision){const note=prompt(decision==='approve'?'Ghi chú thanh toán:':'Lý do từ chối:')||'';try{await adminApi('process_withdrawal',{withdrawal_id:id,decision,note});toast(decision==='approve'?'Đã đánh dấu thanh toán.':'Đã từ chối và hoàn coin.','ok');admin()}catch(x){toast(err(x.message),'bad')}}
async function adjust(id){const amount=Number(prompt('Nhập số coin (+ cộng, - trừ):'));if(!Number.isSafeInteger(amount)||!amount)return;const note=prompt('Lý do điều chỉnh:')||'';try{await adminApi('adjust_coin',{user_id:id,amount,note});toast('Đã điều chỉnh coin.','ok');admin()}catch(x){toast(err(x.message),'bad')}}

async function init(){root.innerHTML='<div class="loader"></div>';const{data}=await supabase.auth.getSession();if(data.session){try{await load()}catch(x){toast(err(x.message),'bad');auth()}}else auth();supabase.auth.onAuthStateChange(async(_,session)=>{if(!session){s.data=null;close();auth();return}if(!s.data){try{await load()}catch(x){toast(err(x.message),'bad')}}})}
init()
